# Generated by Django 3.2.16 on 2022-11-20 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcadYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, null=True)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=50)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.acadyear')),
                ('units', models.ManyToManyField(to='school.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.IntegerField(null=True)),
                ('exam', models.IntegerField(null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=10, null=True)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.acadyear')),
                ('study_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studyyear')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.FloatField(max_length=10, null=True)),
                ('balance', models.FloatField(max_length=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
